server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: localhost:9092

  data:
    mongodb:
      uri: mongodb://localhost:27017/test?retryWrites=true&w=majority

  application:
    name: product-service


logging:
  level:
    com.kgregorczyk: DEBUG